# Generated by Django 2.1.3 on 2019-01-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('raca', models.CharField(max_length=20, verbose_name='Raça')),
                ('cientifico', models.CharField(max_length=20, verbose_name='Nome Científico')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expectativa', models.CharField(max_length=10, verbose_name='Expectativa de Vida')),
                ('objetivo', models.CharField(choices=[('Abate', 'Abate'), ('Reprodutor', 'Reprodutor')], max_length=10)),
            ],
        ),
    ]
