# Generated by Django 2.1.3 on 2019-01-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cientifico', models.CharField(max_length=20, verbose_name='Nome Científico')),
                ('expectativa', models.CharField(max_length=10, verbose_name='Expectativa de Vida')),
                ('periodo', models.CharField(max_length=10, verbose_name='Periodo de Gestação')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('velocidade', models.IntegerField()),
                ('codigo', models.CharField(max_length=11, verbose_name='Código de Identificação')),
                ('raca', models.CharField(max_length=20, verbose_name='Raça')),
                ('objetivo', models.CharField(choices=[('Abate', 'Abate'), ('Reprodutor', 'Reprodutor')], max_length=10)),
            ],
        ),
    ]
