# Generated by Django 2.1.3 on 2019-01-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_fazendeiro_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazendeiro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=3, max_length=1),
            preserve_default=False,
        ),
    ]
