# Generated by Django 2.1.3 on 2019-01-24 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_fazendeiro_sexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='objetivo',
            new_name='tipo_criacao',
        ),
    ]
